# Generated by Django 4.2.7 on 2025-08-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='feels_like',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='visibility',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='weather_main',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
