# Generated by Django 4.2.7 on 2025-08-23 03:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('demand_level', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_website', models.URLField(blank=True)),
                ('export_volume', models.IntegerField(default=0)),
                ('market_share', models.FloatField(default=0.0)),
                ('potential_growth', models.FloatField(default=0.0)),
            ],
        ),
    ]
