# Generated by Django 4.2.7 on 2025-08-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('subsidy', 'Subsidy'), ('loan', 'Loan'), ('insurance', 'Insurance'), ('training', 'Training'), ('equipment', 'Equipment'), ('technology', 'Technology')], max_length=20)),
                ('description', models.TextField()),
                ('eligibility', models.TextField()),
                ('benefits', models.TextField()),
                ('application_process', models.TextField()),
                ('documents_required', models.TextField()),
                ('contact_info', models.TextField()),
                ('website_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
