# Generated by Django 4.2.7 on 2025-08-21 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=20)),
                ('min_temperature', models.FloatField()),
                ('max_temperature', models.FloatField()),
                ('min_rainfall', models.FloatField()),
                ('max_rainfall', models.FloatField()),
                ('soil_ph_min', models.FloatField()),
                ('soil_ph_max', models.FloatField()),
                ('growing_period_days', models.IntegerField()),
                ('suitable_states', models.TextField()),
                ('yield_per_hectare', models.FloatField(help_text='Average yield in tons per hectare')),
                ('market_price_per_kg', models.FloatField(help_text='Average market price per kg')),
            ],
        ),
        migrations.CreateModel(
            name='CropRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_size', models.FloatField()),
                ('location', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('soil_ph', models.FloatField()),
                ('temperature', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('nitrogen', models.FloatField(blank=True, null=True)),
                ('phosphorus', models.FloatField(blank=True, null=True)),
                ('potassium', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suitability_score', models.FloatField()),
                ('expected_yield', models.FloatField()),
                ('expected_profit', models.FloatField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.crop')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_crops', to='crops.croprecommendation')),
            ],
            options={
                'ordering': ['-suitability_score'],
            },
        ),
    ]
