# Generated by Django 4.2.7 on 2025-08-23 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropPriceForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(help_text='Month number (1-12)')),
                ('year', models.IntegerField()),
                ('forecasted_price', models.FloatField(help_text='Forecasted price per kg')),
                ('price_change_percentage', models.FloatField(blank=True, help_text='Percentage change from current price', null=True)),
                ('climate_impact', models.CharField(help_text='Climate impact on price (positive/negative/neutral)', max_length=50)),
                ('market_trend', models.CharField(help_text='Market trend (rising/falling/stable)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_forecasts', to='crops.crop')),
            ],
            options={
                'ordering': ['year', 'month'],
                'unique_together': {('crop', 'month', 'year')},
            },
        ),
    ]
