# Generated by Django 4.2.7 on 2025-08-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_croppriceforecast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croppriceforecast',
            name='climate_impact',
            field=models.CharField(help_text='Climate impact on price (positive/negative/neutral)', max_length=255),
        ),
        migrations.AlterField(
            model_name='croppriceforecast',
            name='forecasted_price',
            field=models.DecimalField(decimal_places=2, help_text='Forecasted price per kg', max_digits=10),
        ),
        migrations.AlterField(
            model_name='croppriceforecast',
            name='market_trend',
            field=models.CharField(help_text='Market trend (rising/falling/stable)', max_length=255),
        ),
        migrations.AlterField(
            model_name='croppriceforecast',
            name='price_change_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage change from current price', max_digits=5, null=True),
        ),
    ]
