# Generated by Django 4.2.7 on 2025-08-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pesticide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('insecticide', 'Insecticide'), ('herbicide', 'Herbicide'), ('fungicide', 'Fungicide'), ('nematicide', 'Nematicide'), ('rodenticide', 'Rodenticide'), ('other', 'Other')], max_length=20)),
                ('active_ingredient', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_pests', models.TextField()),
                ('application_method', models.TextField()),
                ('dosage', models.CharField(max_length=100)),
                ('safety_precautions', models.TextField()),
                ('manufacturer', models.CharField(max_length=200)),
                ('price_range', models.CharField(blank=True, max_length=100)),
                ('is_organic', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
